// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/database/objectbox/entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 466381110667171496),
    name: 'DuplicateGroup',
    lastPropertyId: const obx_int.IdUid(3, 8715003966604002938),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7213673854422414146),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2777658974738769110),
        name: 'groupHash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8715003966604002938),
        name: 'foundAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'members',
        srcEntity: 'DuplicateMember',
        srcField: 'group',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1673547060900335371),
    name: 'DuplicateMember',
    lastPropertyId: const obx_int.IdUid(5, 7110732834139189988),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2583873460436993160),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6455725102917339941),
        name: 'assetId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2026590420928672865),
        name: 'phash',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5810386753480990983),
        name: 'hammingDistance',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7110732834139189988),
        name: 'groupId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 5935365044012149312),
        relationField: 'group',
        relationTarget: 'DuplicateGroup',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6843951167299019905),
    name: 'MediaAnalysis',
    lastPropertyId: const obx_int.IdUid(10, 8851362538303239846),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9205971078144043680),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1179442140568667096),
        name: 'assetId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 409617396114259788),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5064314375744927513),
        name: 'aiCaption',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3175241220694051035),
        name: 'extractedText',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3605837666318613069),
        name: 'sentiment',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6663633047255907547),
        name: 'credibilityScore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2463094390669097936),
        name: 'labelsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7442208732386933648),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 3289520274905075004),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3457847204058994215),
        name: 'analyzedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8851362538303239846),
        name: 'isAnalyzed',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2942759972950401537),
    name: 'PersonAsset',
    lastPropertyId: const obx_int.IdUid(3, 6935739115043102364),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1580489261297542554),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6866483896111059400),
        name: 'assetId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6935739115043102364),
        name: 'personId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 8588067920604260836),
        relationField: 'person',
        relationTarget: 'PersonGroup',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 7973799645742335597),
    name: 'PersonGroup',
    lastPropertyId: const obx_int.IdUid(5, 1167887161658848471),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7495853925516010184),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2789099773216262713),
        name: 'groupId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2102451205337737707),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3022320504656237334),
        name: 'coverAssetId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1167887161658848471),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'assets',
        srcEntity: 'PersonAsset',
        srcField: 'person',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 9000331004368135959),
    name: 'SecureFile',
    lastPropertyId: const obx_int.IdUid(3, 5328509157888539740),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8963472375488746625),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 510070222925384622),
        name: 'assetId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(5, 6611171340407742716),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5328509157888539740),
        name: 'addedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 9000331004368135959),
    lastIndexId: const obx_int.IdUid(5, 6611171340407742716),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DuplicateGroup: obx_int.EntityDefinition<DuplicateGroup>(
      model: _entities[0],
      toOneRelations: (DuplicateGroup object) => [],
      toManyRelations: (DuplicateGroup object) => {
        obx_int.RelInfo<DuplicateMember>.toOneBacklink(
          5,
          object.id,
          (DuplicateMember srcObject) => srcObject.group,
        ): object.members,
      },
      getId: (DuplicateGroup object) => object.id,
      setId: (DuplicateGroup object, int id) {
        object.id = id;
      },
      objectToFB: (DuplicateGroup object, fb.Builder fbb) {
        final groupHashOffset = fbb.writeString(object.groupHash);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupHashOffset);
        fbb.addInt64(2, object.foundAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final groupHashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final foundAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = DuplicateGroup(
          id: idParam,
          groupHash: groupHashParam,
          foundAt: foundAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<DuplicateGroup>(
          object.members,
          store,
          obx_int.RelInfo<DuplicateMember>.toOneBacklink(
            5,
            object.id,
            (DuplicateMember srcObject) => srcObject.group,
          ),
        );
        return object;
      },
    ),
    DuplicateMember: obx_int.EntityDefinition<DuplicateMember>(
      model: _entities[1],
      toOneRelations: (DuplicateMember object) => [object.group],
      toManyRelations: (DuplicateMember object) => {},
      getId: (DuplicateMember object) => object.id,
      setId: (DuplicateMember object, int id) {
        object.id = id;
      },
      objectToFB: (DuplicateMember object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        final phashOffset = fbb.writeString(object.phash);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addOffset(2, phashOffset);
        fbb.addInt64(3, object.hammingDistance);
        fbb.addInt64(4, object.group.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phashParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final hammingDistanceParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = DuplicateMember(
          id: idParam,
          assetId: assetIdParam,
          phash: phashParam,
          hammingDistance: hammingDistanceParam,
        );
        object.group.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.group.attach(store);
        return object;
      },
    ),
    MediaAnalysis: obx_int.EntityDefinition<MediaAnalysis>(
      model: _entities[2],
      toOneRelations: (MediaAnalysis object) => [],
      toManyRelations: (MediaAnalysis object) => {},
      getId: (MediaAnalysis object) => object.id,
      setId: (MediaAnalysis object, int id) {
        object.id = id;
      },
      objectToFB: (MediaAnalysis object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        final aiCaptionOffset = object.aiCaption == null
            ? null
            : fbb.writeString(object.aiCaption!);
        final extractedTextOffset = object.extractedText == null
            ? null
            : fbb.writeString(object.extractedText!);
        final sentimentOffset = object.sentiment == null
            ? null
            : fbb.writeString(object.sentiment!);
        final labelsJsonOffset = object.labelsJson == null
            ? null
            : fbb.writeString(object.labelsJson!);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addOffset(2, aiCaptionOffset);
        fbb.addOffset(3, extractedTextOffset);
        fbb.addOffset(4, sentimentOffset);
        fbb.addFloat64(5, object.credibilityScore);
        fbb.addOffset(6, labelsJsonOffset);
        fbb.addOffset(7, embeddingOffset);
        fbb.addInt64(8, object.analyzedAt.millisecondsSinceEpoch);
        fbb.addBool(9, object.isAnalyzed);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final aiCaptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final extractedTextParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final sentimentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final credibilityScoreParam = const fb.Float64Reader()
            .vTableGetNullable(buffer, rootOffset, 14);
        final labelsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final embeddingParam = const obx_int.Float32ListReader()
            .vTableGetNullable(buffer, rootOffset, 18);
        final analyzedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final isAnalyzedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          22,
          false,
        );
        final object = MediaAnalysis(
          id: idParam,
          assetId: assetIdParam,
          aiCaption: aiCaptionParam,
          extractedText: extractedTextParam,
          sentiment: sentimentParam,
          credibilityScore: credibilityScoreParam,
          labelsJson: labelsJsonParam,
          embedding: embeddingParam,
          analyzedAt: analyzedAtParam,
          isAnalyzed: isAnalyzedParam,
        );

        return object;
      },
    ),
    PersonAsset: obx_int.EntityDefinition<PersonAsset>(
      model: _entities[3],
      toOneRelations: (PersonAsset object) => [object.person],
      toManyRelations: (PersonAsset object) => {},
      getId: (PersonAsset object) => object.id,
      setId: (PersonAsset object, int id) {
        object.id = id;
      },
      objectToFB: (PersonAsset object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addInt64(2, object.person.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final object = PersonAsset(id: idParam, assetId: assetIdParam);
        object.person.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.person.attach(store);
        return object;
      },
    ),
    PersonGroup: obx_int.EntityDefinition<PersonGroup>(
      model: _entities[4],
      toOneRelations: (PersonGroup object) => [],
      toManyRelations: (PersonGroup object) => {
        obx_int.RelInfo<PersonAsset>.toOneBacklink(
          3,
          object.id,
          (PersonAsset srcObject) => srcObject.person,
        ): object.assets,
      },
      getId: (PersonGroup object) => object.id,
      setId: (PersonGroup object, int id) {
        object.id = id;
      },
      objectToFB: (PersonGroup object, fb.Builder fbb) {
        final groupIdOffset = fbb.writeString(object.groupId);
        final nameOffset = fbb.writeString(object.name);
        final coverAssetIdOffset = object.coverAssetId == null
            ? null
            : fbb.writeString(object.coverAssetId!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, groupIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, coverAssetIdOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final groupIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final coverAssetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final object = PersonGroup(
          id: idParam,
          groupId: groupIdParam,
          name: nameParam,
          coverAssetId: coverAssetIdParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<PersonGroup>(
          object.assets,
          store,
          obx_int.RelInfo<PersonAsset>.toOneBacklink(
            3,
            object.id,
            (PersonAsset srcObject) => srcObject.person,
          ),
        );
        return object;
      },
    ),
    SecureFile: obx_int.EntityDefinition<SecureFile>(
      model: _entities[5],
      toOneRelations: (SecureFile object) => [],
      toManyRelations: (SecureFile object) => {},
      getId: (SecureFile object) => object.id,
      setId: (SecureFile object, int id) {
        object.id = id;
      },
      objectToFB: (SecureFile object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addInt64(2, object.addedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = SecureFile(
          id: idParam,
          assetId: assetIdParam,
          addedAt: addedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DuplicateGroup] entity fields to define ObjectBox queries.
class DuplicateGroup_ {
  /// See [DuplicateGroup.id].
  static final id = obx.QueryIntegerProperty<DuplicateGroup>(
    _entities[0].properties[0],
  );

  /// See [DuplicateGroup.groupHash].
  static final groupHash = obx.QueryStringProperty<DuplicateGroup>(
    _entities[0].properties[1],
  );

  /// See [DuplicateGroup.foundAt].
  static final foundAt = obx.QueryDateProperty<DuplicateGroup>(
    _entities[0].properties[2],
  );

  /// see [DuplicateGroup.members]
  static final members =
      obx.QueryBacklinkToMany<DuplicateMember, DuplicateGroup>(
        DuplicateMember_.group,
      );
}

/// [DuplicateMember] entity fields to define ObjectBox queries.
class DuplicateMember_ {
  /// See [DuplicateMember.id].
  static final id = obx.QueryIntegerProperty<DuplicateMember>(
    _entities[1].properties[0],
  );

  /// See [DuplicateMember.assetId].
  static final assetId = obx.QueryStringProperty<DuplicateMember>(
    _entities[1].properties[1],
  );

  /// See [DuplicateMember.phash].
  static final phash = obx.QueryStringProperty<DuplicateMember>(
    _entities[1].properties[2],
  );

  /// See [DuplicateMember.hammingDistance].
  static final hammingDistance = obx.QueryIntegerProperty<DuplicateMember>(
    _entities[1].properties[3],
  );

  /// See [DuplicateMember.group].
  static final group = obx.QueryRelationToOne<DuplicateMember, DuplicateGroup>(
    _entities[1].properties[4],
  );
}

/// [MediaAnalysis] entity fields to define ObjectBox queries.
class MediaAnalysis_ {
  /// See [MediaAnalysis.id].
  static final id = obx.QueryIntegerProperty<MediaAnalysis>(
    _entities[2].properties[0],
  );

  /// See [MediaAnalysis.assetId].
  static final assetId = obx.QueryStringProperty<MediaAnalysis>(
    _entities[2].properties[1],
  );

  /// See [MediaAnalysis.aiCaption].
  static final aiCaption = obx.QueryStringProperty<MediaAnalysis>(
    _entities[2].properties[2],
  );

  /// See [MediaAnalysis.extractedText].
  static final extractedText = obx.QueryStringProperty<MediaAnalysis>(
    _entities[2].properties[3],
  );

  /// See [MediaAnalysis.sentiment].
  static final sentiment = obx.QueryStringProperty<MediaAnalysis>(
    _entities[2].properties[4],
  );

  /// See [MediaAnalysis.credibilityScore].
  static final credibilityScore = obx.QueryDoubleProperty<MediaAnalysis>(
    _entities[2].properties[5],
  );

  /// See [MediaAnalysis.labelsJson].
  static final labelsJson = obx.QueryStringProperty<MediaAnalysis>(
    _entities[2].properties[6],
  );

  /// See [MediaAnalysis.embedding].
  static final embedding = obx.QueryHnswProperty<MediaAnalysis>(
    _entities[2].properties[7],
  );

  /// See [MediaAnalysis.analyzedAt].
  static final analyzedAt = obx.QueryDateProperty<MediaAnalysis>(
    _entities[2].properties[8],
  );

  /// See [MediaAnalysis.isAnalyzed].
  static final isAnalyzed = obx.QueryBooleanProperty<MediaAnalysis>(
    _entities[2].properties[9],
  );
}

/// [PersonAsset] entity fields to define ObjectBox queries.
class PersonAsset_ {
  /// See [PersonAsset.id].
  static final id = obx.QueryIntegerProperty<PersonAsset>(
    _entities[3].properties[0],
  );

  /// See [PersonAsset.assetId].
  static final assetId = obx.QueryStringProperty<PersonAsset>(
    _entities[3].properties[1],
  );

  /// See [PersonAsset.person].
  static final person = obx.QueryRelationToOne<PersonAsset, PersonGroup>(
    _entities[3].properties[2],
  );
}

/// [PersonGroup] entity fields to define ObjectBox queries.
class PersonGroup_ {
  /// See [PersonGroup.id].
  static final id = obx.QueryIntegerProperty<PersonGroup>(
    _entities[4].properties[0],
  );

  /// See [PersonGroup.groupId].
  static final groupId = obx.QueryStringProperty<PersonGroup>(
    _entities[4].properties[1],
  );

  /// See [PersonGroup.name].
  static final name = obx.QueryStringProperty<PersonGroup>(
    _entities[4].properties[2],
  );

  /// See [PersonGroup.coverAssetId].
  static final coverAssetId = obx.QueryStringProperty<PersonGroup>(
    _entities[4].properties[3],
  );

  /// See [PersonGroup.createdAt].
  static final createdAt = obx.QueryDateProperty<PersonGroup>(
    _entities[4].properties[4],
  );

  /// see [PersonGroup.assets]
  static final assets = obx.QueryBacklinkToMany<PersonAsset, PersonGroup>(
    PersonAsset_.person,
  );
}

/// [SecureFile] entity fields to define ObjectBox queries.
class SecureFile_ {
  /// See [SecureFile.id].
  static final id = obx.QueryIntegerProperty<SecureFile>(
    _entities[5].properties[0],
  );

  /// See [SecureFile.assetId].
  static final assetId = obx.QueryStringProperty<SecureFile>(
    _entities[5].properties[1],
  );

  /// See [SecureFile.addedAt].
  static final addedAt = obx.QueryDateProperty<SecureFile>(
    _entities[5].properties[2],
  );
}
